# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://netzzwergeGithub.github.io',
                'git_url': 'https://github.com/netzzwergeGithub/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.cards': {'nbdev_hello_world.cards.foo': ('cards.html#foo', 'nbdev_hello_world/cards.py')},
            'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')}}}
